feat(pre-commit shell script): now the logs of the test are saved in a txt file

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,8 +1,15 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-echo $@
-exit 210
+logFileName="test-logs.txt"
+set -o pipefail
+echo "" | tee $logFileName
+echo "--------------------------" | tee -a $logFileName
+echo "Starting Pre Commit Tests." | tee -a $logFileName
+echo `date +"%A, %Y-%m-%d %T"` | tee -a $logFileName
+echo "--------------------------" | tee -a $logFileName
+echo "" | tee -a $logFileName
+
 
 declare -a commands=(
     "yarn build"
@@ -13,6 +20,7 @@ declare -a commands=(
 )
 declare -i progress=1
 
+RED='\033[0;31m'
 BLUE='\033[0;36m'
 GRAY='\033[1;30m'
 NC='\033[0m'
@@ -22,7 +30,8 @@ for i in "${!commands[@]}"
 do  
     echo -e "\n${BLUE}Running Pre Commit test : [""${progress}/${#commands[@]}""]${NC}"
     echo -e "${GRAY}${commands[$i]}\n${NC}"
-    eval "${commands[$i]}"
+    eval "${commands[$i]}" | tee -a $logFileName || { echo -e "\n${RED}${commands[$i]} Failed!\nSee ${logFileName} for details.\n${NC}"; exit 212; }
     echo -e "${BGreen}Passed [""${progress}/${#commands[@]}""]${NC}\n"
     ((progress++))
 done
+
